spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
gemini.api.key=AIzaSyDRg0k62Ikg6upqFF0HRjoNh5e7xgpBPRY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
aws.access.key=erftgyhuiopj
aws.secret.key=dfcgbhjknmlcgvhbjnk
aws.region=eu-north-1
aws.bucket.name=billing-software-ankit

jwt.secret.key=Rd/ziQ1JWaFH8bjG44kYhU7F7b9HZ2S3t0oQ4dlQQMQ=
razorpay.key.id=dfcgbvhjnkmn
razorpay.key.secret=fyghjklbjnkm

